# Generated by Django 5.1 on 2024-08-20 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=50)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_phone', models.IntegerField()),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('outstanding_debt', models.IntegerField(default=0)),
                ('books_issued', models.PositiveIntegerField(default=0)),
                ('last_settlement_date', models.DateField(blank=True, null=True)),
                ('last_settled_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('issue_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField()),
                ('overdue', models.IntegerField(default=0)),
                ('fine', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('issued_to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.members')),
            ],
        ),
    ]
